### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Memorix101** [Memorix101/SharpQuake#2]
### TODO List
- [ ] Server browser doesn't show local games
- [ ] Implement playback of music inside a music folder e.g. `Id1\music\track01.ogg`
- [ ] Try to make this playable on Mac (OpenGL is broken there) 😕
- [ ] Add [MonoKickstart](https://github.com/OutOfOrder/MonoKickstart) for Unix platforms
- [ ] Show error message box without Windows.Forms (as on Mac 64bit it's broken) 
- [ ] Windowed mode is somehow broken on Linux (won't launch sometimes)
- [ ] Fix lower-case file names on Linux (renaming files is annoying)
- [ ] Cleanup and restructure the code (strip down the GLQuake code and modernise it) `"you still need voodoo graphics or 3dfx?"`

### Notes
- SDL2 backend in OpenTK 3.0 is somehow broken and will result in bad mouse position bugs. It's not possible to use this. However, a workaround to still use SDL2 outside of OpenTK with [SDL2-CS](https://github.com/flibitijibibo/SDL2-CS) I added a line of code to turn off the SDL2 detection in OpenTK.
