### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Memorix101** [Memorix101/SharpQuake#3]
### TODO List
- [x] Can't connect to local games from server browser as host IP is always 0.0.0.0:PORT
- [x] Implement music playback  inside a folder e.g. `Id1\music\track01.ogg` ([Restore music playback](https://pcgamingwiki.com/wiki/Quake#Restore_music_playback))
- [x] Show message box without Windows.Forms (as on Mac 64bit it's broken) 
- [x] Windowed mode is somehow broken on Linux
- [x] Fix lower-case file names on Linux (renaming files is annoying)
- [x] Cleanup and restructure/modernise the code (Thanks to @optimus-code)
- [ ] Make it possible to run [mod episodes](https://www.moddb.com/mods/its)

### Please take a look into this
- [ ] Server browser doesn't update connected player count (in some scenarios like crashes ...)
- [ ] Add [MonoKickstart](https://github.com/OutOfOrder/MonoKickstart) for Unix platforms
- [x]  Music playback for mission packs not working correctly
- [ ] [Try to make this playable on Mac](https://youtu.be/DmpmJJADJw8) ([OpenGL is broken/deprecated there](https://developer.apple.com/macos/whats-new/)) 😕
- [ ]  Make model animations more smooth

### Notes
- SDL2 backend in OpenTK 3.0 is somehow broken and will result in bad mouse position bugs. It's not possible to use this. However, as a workaround to use SDL2 outside of OpenTK with [SDL2-CS](https://github.com/flibitijibibo/SDL2-CS) I added a line of code to turn off the SDL2 detection in OpenTK.

### Mod episodes compatiblity
❌ Nope | 🔶 With issues | ✔ Perfect
- ❌[Arcane Dimensions - 1.5](https://www.quaddicted.com/reviews/ad_v1_50final.html)
- ❌ [In The Shadows - Demo Version 1.1](https://www.quaddicted.com/reviews/its_demo_v1_1.html)
- ❌[X-Men: The Ravages of Apocalypse TC](https://www.moddb.com/mods/x-men-ravages-of-apocalypse/downloads/x-men-ravages-of-apocalypse-tc)
